### ISSUE TITLE
Dose not work on mobile

### ISSUE THREAD

**Issue by GameStuffOffical** [Anuken/MindustryBuilds#10]
Your character dose not move

**Comment by Anuken** [comment]
Are you incapable of reading?

**Comment by GameStuffOffical** [comment]
Dear Anuken. I'm sorry Anuke for wasting your time. Just it would be nice
if you could implement it, And I am very impressed with your work and how
you are able to respond to me.
Sincerely, Mindustry fan ,Game Stuff
