### ISSUE TITLE
Mindustry BE crashing when you proceed further from ground zero

### ISSUE THREAD

**Issue by mindustry12** [Anuken/MindustryBuilds#11]

**Comment by mindustry12** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/67495436/85915204-110ef280-b878-11ea-9985-5dbaf284df2c.png)
![Screenshot (1)](https://user-images.githubusercontent.com/67495436/85915205-110ef280-b878-11ea-93dc-91ae6915c6c7.png)

**Comment by mindustry12** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/67495436/85915224-24ba5900-b878-11ea-838a-fd3a31095941.png)

**Comment by Anuken** [comment]
1. Don't play 6.0. It's not ready for testing.
2. If you do, at least **read the issue template** and do what it tells you to. Why did you explicitly erase the contents of the template?
