### ISSUE TITLE
Auto Power Nodes 5847

### ISSUE THREAD

**Issue by CaptainCosmotic** [Anuken/MindustryBuilds#4]
In Version 5847 the Big power Nodes doesn't connect in the maximum possible way compared to manual placing. 
Screenshot top line auto connect
bottom line manual connection. 
Small power node connection seems to work fine.
![auto power nodes](https://user-images.githubusercontent.com/57239116/68660473-845a3300-0539-11ea-839a-a79caac12550.png)

**Comment by Anuken** [comment]
Fixed. In the future, report issues in the main Mindustry repository, not here.
